---

- name: Wait 300 seconds, but only start checking after 60 seconds
  wait_for_connection:
    delay: 30
    timeout: 60
    
- name: install chrome
  become: true
  shell: |
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dpkg -i google-chrome-stable_current_amd64.deb
    sudo apt-get install -f
