---
- name: Check Google Chrome Installation
  ansible.builtin.shell: google-chrome --version
  register: chrome_output
  ignore_errors: true

- name: Install Google Chrome Package
  become: yes
  block:
    - name: Update apt Packages
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Download Google Chrome Package
      ansible.builtin.get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /tmp/
        force_basic_auth: yes
      register: download
      
    - name: Installing Google Chrome
      ansible.builtin.shell: dpkg -i /tmp/google-chrome-stable_current_amd64.deb
      when: download is defined

    - name: Cleanup Memory
      ansible.builtin.shell: rm -rf /tmp/google-chrome-stable_current_amd64.deb
      when: download is defined
  when: chrome_output.rc != 1
